### PR TITLE
Upgrade dependencies

### PR DESCRIPTION
**Pull request by nhuyvan**
This change is [Reviewable](https://reviewable.io/reviews/gridappsd/gridappsd-viz/419)

### CODE REVIEW

**Comment by bibiraju** [comment]
Does this have any other feature? Or only the dependency upgrade?

**Comment by nhuyvan** [comment]
> Does this have any other feature? Or only the dependency upgrade?

The table in Browse Data > LOGS was redesigned

**Comment by bibiraju** [comment]
Looks like you changed frontend to client and backend to server? Are the folders frontend and backend still being used?

**Comment by nhuyvan** [comment]
> Looks like you changed frontend to client and backend to server? Are the folders frontend and backend still being used?

I renamed those folders and updated any references to the old names with the new names

**Pull request merged**
