### PR TITLE
For release

### PR DESCRIPTION
**Pull request by nhuyvan1106**
This change is [Reviewable](https://reviewable.io/reviews/gridappsd/gridappsd-viz/42)

### CODE REVIEW

**Comment by craig8** [comment]
@nhuyvan1106 please merge back from develop into your for-release branch as it probably has some references that should be updated.

In addtion, I attempted building this but got the following error.  Any help with it would be appreciated.

````
    
    ERROR in ./node_modules/css-loader!./node_modules/sass-loader/lib/loader.js!./src/app/shared/views/form/select-form-control/SelectFormControl.scss
    Module build failed: Error: `sass-loader` requires `node-sass` >=4. Please install a compatible version.
        at Object.sassLoader (/gridappsd/viz/node_modules/sass-loader/lib/loader.js:31:19)
Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js!node_modules/sass-loader/lib/loader.js!src/app/shared/views/form/form-control/FormControl.scss:
       [0] ./node_modules/css-loader!./node_modules/sass-loader/lib/loader.js!./src/app/shared/views/form/form-control/FormControl.scss 212 bytes {0} [built] [failed] [1 error]
    
    ERROR in ./node_modules/css-loader!./node_modules/sass-loader/lib/loader.js!./src/app/shared/views/form/form-control/FormControl.scss
    Module build failed: Error: `sass-loader` requires `node-sass` >=4. Please install a compatible version.
        at Object.sassLoader (/gridappsd/viz/node_modules/sass-loader/lib/loader.js:31:19)
Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js!node_modules/sass-loader/lib/loader.js!src/app/shared/views/form/form-group/FormGroup.scss:
       [0] ./node_modules/css-loader!./node_modules/sass-loader/lib/loader.js!./src/app/shared/views/form/form-group/FormGroup.scss 212 bytes {0} [built] [failed] [1 error]
    
    ERROR in ./node_modules/css-loader!./node_modules/sass-loader/lib/loader.js!./src/app/shared/views/form/form-group/FormGroup.scss
    Module build failed: Error: `sass-loader` requires `node-sass` >=4. Please install a compatible version.
        at Object.sassLoader (/gridappsd/viz/node_modules/sass-loader/lib/loader
````

**Comment by bibiraju** [comment]
Did you change the node version? Try npm rebuild --force.

**Comment by craig8** [comment]
@bibiraju I built with the container...so that should be set up to just work...I believe.  @tonya1 perhaps can take a look?

**Comment by nhuyvan1106** [comment]
@craig8 I really have no idea why the build intermittently fails, but looks like it succeeded this time

**Comment by craig8** [comment]
@nhuyvan1106 perhaps it was merging develop back into the branch...not sure...I will attempt to rebuild it on my system with docker and let you know.

**Pull request merged**
