### PR TITLE
New authentication scheme

### PR DESCRIPTION
**Pull request by nhuyvan**
This PR depends on the platform merging in its new authentication mechanism, Poorva or Tara can let Bibi know when that's ready for her to merge this PR into Viz.

This new PR replaced this one https://github.com/GRIDAPPSD/gridappsd-viz/pull/352, it fixed the authentication problem that  Poorva reported earlier, also fixed some merge conflicts.

---
This change is [Reviewable](https://reviewable.io/reviews/gridappsd/gridappsd-viz/366)

### CODE REVIEW

**Comment by poorva1209** [comment]
@nhuyvan the previous issue is resolved. But if I am already logged in and then Sign out then I cannot log back in.

**Comment by nhuyvan** [comment]
@poorva1209  I wasn't able to reproduce your issue at all

**Comment by poorva1209** [comment]
Now I am not even able to log in. I will rebuild the Viz container and try it again. I will setup a call with you if this problem persists.

**Comment by nhuyvan** [comment]
@poorva1209 @bibiraju  Please pull the latest changes and try again

**Pull request merged**
