### PR TITLE
Now clicking on simulation ID will copy it to clipboard

### PR DESCRIPTION
**Pull request by nhuyvan**
This change is [Reviewable](https://reviewable.io/reviews/gridappsd/gridappsd-viz/102)

### CODE REVIEW

**Comment by bibiraju** [comment]
When I click on simulation id it says copied to clipboard but when I try to paste, I see that it's not copied. However I am able to double click on simulation id and select it and then copy it. So fix it to copy when you click on it or remove the tooltip which says it's copied to clipboard.

**Comment by nhuyvan** [comment]
@bibiraju which browser did you test it on?

**Comment by bibiraju** [comment]
Google Chrome

**Comment by nhuyvan** [comment]
@bibiraju It is fixed now

**Comment by bibiraju** [comment]
Copying to clipboard is working. But why is it showing random simulation id even before starting a simulation? Also topology is not rendered on safari.

**Comment by nhuyvan** [comment]
@bibiraju I forgot to remove the dummy simulation ID used to testing, it should be gone now.
Safari for some reason does not take the width and height from CSS, a new PR for it will be created shortly

**Pull request merged**
