### PR TITLE
Add a configuration file allowing to change version and host at runtime

### PR DESCRIPTION
**Pull request by nhuyvan**
This change is [Reviewable](https://reviewable.io/reviews/gridappsd/gridappsd-viz/114)

### CODE REVIEW

**Comment by bibiraju** [comment]
@craig can you test this with docker to see if this is what you wanted for changing host url

**Comment by tonya1** [comment]
Changing the version at build time no longer works.

Using a local config.json file mounted through docker-compose allows the viz to work on a separate machine from the platform, the simulation fails.

Error while calling REST Service
javax.ws.rs.InternalServerErrorException: HTTP 500 Internal Server Error
Attempting to start remote app on goss.gridappsd.remoteapp.start.sample_app
WATCHING fncs-1562200698256
WATCHING fncsgossbridge-1562200698276
Thread-59 ERROR [gov.pnnl.goss.gridappsd.log.LogManagerImpl] - 1562200748520|SimulationProcess|341266783|ERROR|system|ERROR
FNCS Initialization Failed

Stopping app: sample_app
Thread-38 ERROR [gov.pnnl.goss.gridappsd.log.LogManagerImpl] - 1562200748000|fncs_goss_bridge.py|341266783|ERROR|system|ERROR
fncs.initialize(configuration_zpl) failed!
configuration_zpl = name = FNCS_GOSS_Bridge_341266783
time_delta = 1s
broker = tcp://127.0.0.1:52917
values
    341266783
        topic = 341266783/fncs_output
        default = {}
        type = JSON
        list = false

**Comment by tonya1** [comment]
With the latest platform updates the REST error is resolved.  Changing the version at build time no longer works.

**Comment by craig** [comment]
> @craig can you test this with docker to see if this is what you wanted for changing host url

no

**Comment by nhuyvan** [comment]
@tonya1 when I tested it with `npm run build hello-world`, it succeeded for me, can you elaborate on what happened?

**Comment by tonya1** [comment]
Nhuy,

Is it possible the version specified in the config.json file is overwriting the version set in the build?  Does the config.json file also need to be updated at build time?

Tonya

**Comment by nhuyvan** [comment]
@tonya1 The build script will take the value you pass to it via the build command, e.g. `npm run build hello-world`, the build script will take `hello-world` and write it to `config.json` for the version number, can you look inside the file `webpack.config.js` at line 112 and see if the file name being written to is `config.json`?

**Comment by tonya1** [comment]
@nhuyvan - I was able to verify the build version updated.  Can you resolve the conflicting files?

**Pull request merged**
