### PR TITLE
Only show a fixed number of log messages at a time, and load more whe…

### PR DESCRIPTION
**Pull request by nhuyvan**
…n the scroll bar is at the bottom of the container

---
This change is [Reviewable](https://reviewable.io/reviews/gridappsd/gridappsd-viz/130)

### CODE REVIEW

**Comment by bibiraju** [comment]
@nhuyvan I don't see any logs with this change.

**Comment by nhuyvan** [comment]
@bibiraju Please test the new commit

**Comment by bibiraju** [comment]
@nhuyvan this looks good. Can you also remove the numbering for logs? It doesn't make sense to keep the numbering now as the logs are showing in reversed order and is confusing.

**Comment by nhuyvan** [comment]
@bibiraju The numbering should be removed now

**Pull request merged**
