### PR TITLE
[GRIDAPPSD/GOSS-GridAPPS-D#1073] Send forward/reverse difference valu…

### PR DESCRIPTION
**Pull request by nhuyvan**
…es as integers instead of strings

---
This change is [Reviewable](https://reviewable.io/reviews/gridappsd/gridappsd-viz/165)

### CODE REVIEW

**Comment by bibiraju** [comment]
@nhuyvan we need to change the boolean values to boolean rather than string and numbers should be sent as numbers instead of string.

**Comment by nhuyvan** [comment]
@bibiraju I'm a little confused, doesn't this task https://github.com/gridappsd/goss-gridapps-d/issues/1073 say to use numbers when toggling the switches?

**Comment by bibiraju** [comment]
@nhuyvan it says only switches in the issue but discussed with Andy yesterday and we need to change it for regulators and capacitors too. So where ever we have value as boolean or number we should send it in the right format instead of string.

**Comment by nhuyvan** [comment]
@bibiraju I've made the changes where I deemed necessary to reflect the correct data formats

**Comment by bibiraju** [comment]
I tested it and looks good to me.
@afisher1 Can you test this PR and merge it, if the Viz is sending the correct datatypes for various actions on Switches, Capacitor and Regulator.

**Pull request merged**
